### ISSUE TITLE
Optimise for low memory?

### ISSUE THREAD

**Issue by sm0kew0n** [fogleman/ribbon#2]
HI, I've built this on a low memory embedded system and it runs out of memory when rendering. I noticed in your example code that it renders a 1920x1080 image, is this default? How can I specify image size or optimise for low memory system?

Thanks.

**Comment by adyavanapalli** [comment]
Not sure whether @fogleman is going to answer this (or you already have an answer), but the file `ride.go` in `ribbon/scripts/ride.go` has a section:
```
const (
        scale  = 1
        width  = 1920
        height = 1080
        fovy   = 60
        near   = 0.1
        far    = 100
)
```

Tweaking this and rebuilding might be what you're looking for.

**Comment by sm0kew0n** [comment]
Thanks @adyavanapalli I did tweak that file and with a large swap file managed to render an image. However the render process was unacceptable long (over an hour) so unfortunately not suitable for my system.
